version = "1"
name = "TODO comments checker"
description = "Finds the TODO comments in codebase."
analysis_command = "/app/macro-go"
category = "language"
visibility = "public"

[analyzer]
  command = "/app/macro-go"

[build]
  image = "golang:1.17.6-alpine3.15"
  steps = """
  apk add --no-cache go openssh
  export GOROOT=/usr/lib/go
  export GOPATH=/go
  export PATH=/go/bin:${PATH}
  mkdir -p ${GOPATH}/src ${GOPATH}/bin
  cp -r ../../. /app
  git config --global url.git@github.com:.insteadOf https://github.com/
  go env -w GOPRIVATE=github.com/siddhant-deepsource/*
  cd /app && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/macro-go .
  """
